CREATE TYPE "public"."admin_permission" AS ENUM('compliance_admin');--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'PERMISSION_GRANTED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'PERMISSION_REVOKED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'COMPLIANCE_REAUTH_SUCCEEDED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'COMPLIANCE_REAUTH_FAILED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'PURCHASE_LIMIT_RULE_PUBLISHED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'PURCHASE_LIMIT_RULE_SUPERSEDED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'PURCHASE_LIMIT_RULE_REJECTED';--> statement-breakpoint
CREATE TABLE "user_permissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"permission" "admin_permission" NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"granted_by" uuid,
	"revoked_at" timestamp with time zone,
	"revoked_by" uuid,
	"reason" text
);
--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "purchase_limit_rule_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "change_reason" text;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "published_by" uuid;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "published_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "reauthenticated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "supersedes_rule_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "superseded_by_rule_id" uuid;--> statement-breakpoint
ALTER TABLE "user_permissions" ADD CONSTRAINT "user_permissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_permissions" ADD CONSTRAINT "user_permissions_granted_by_users_id_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_permissions" ADD CONSTRAINT "user_permissions_revoked_by_users_id_fk" FOREIGN KEY ("revoked_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "user_permissions_active_unique" ON "user_permissions" USING btree ("user_id","permission") WHERE "user_permissions"."revoked_at" is null;--> statement-breakpoint
CREATE INDEX "user_permissions_user_idx" ON "user_permissions" USING btree ("user_id");--> statement-breakpoint
ALTER TABLE "order_lines" ADD CONSTRAINT "order_lines_purchase_limit_rule_id_purchase_limit_rules_id_fk" FOREIGN KEY ("purchase_limit_rule_id") REFERENCES "public"."purchase_limit_rules"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD CONSTRAINT "purchase_limit_rules_published_by_users_id_fk" FOREIGN KEY ("published_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD CONSTRAINT "purchase_limit_rules_supersedes_rule_id_purchase_limit_rules_id_fk" FOREIGN KEY ("supersedes_rule_id") REFERENCES "public"."purchase_limit_rules"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD CONSTRAINT "purchase_limit_rules_superseded_by_rule_id_purchase_limit_rules_id_fk" FOREIGN KEY ("superseded_by_rule_id") REFERENCES "public"."purchase_limit_rules"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "purchase_limit_rules_history_idx" ON "purchase_limit_rules" USING btree ("cannabis_class","effective_from");--> statement-breakpoint
CREATE UNIQUE INDEX "purchase_limit_rules_class_version" ON "purchase_limit_rules" USING btree ("cannabis_class","version");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Everything below is hand-written and is NOT generated by drizzle-kit.
--
-- Drizzle models tables; it does not model the guarantee that makes this table
-- worth having. `purchase_limit_rules` records the legal basis on which cannabis
-- was sold to a named person on a named day. If a row can be edited, that basis
-- can be rewritten after the fact; if a row can be deleted, an order can be left
-- citing nothing. Neither may be possible, including to a future maintainer with
-- a psql prompt and a good reason.
--
-- So the guarantee lives in the database, not in the application that happens to
-- be in front of it today.
-- ---------------------------------------------------------------------------

-- Rows that predate versioning have no author. Record that, rather than
-- inventing one.
UPDATE "purchase_limit_rules"
   SET "change_reason" = 'Seeded before rule versioning. Values taken from FALLBACK_LIMIT_RULES and pending legal confirmation.'
 WHERE "change_reason" IS NULL;--> statement-breakpoint

-- A window that ends before it starts is not a window.
ALTER TABLE "purchase_limit_rules"
  ADD CONSTRAINT "purchase_limit_rules_window_ordered"
  CHECK ("effective_until" IS NULL OR "effective_until" >= "effective_from");--> statement-breakpoint

CREATE OR REPLACE FUNCTION purchase_limit_rules_guard() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'purchase_limit_rules is append-only: rule % may not be deleted', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- The value columns. None of these may change once published, because an
  -- order line cites this row as the rule it was checked against.
  IF NEW.id                          IS DISTINCT FROM OLD.id
  OR NEW.cannabis_class              IS DISTINCT FROM OLD.cannabis_class
  OR NEW.version                     IS DISTINCT FROM OLD.version
  OR NEW.equivalent_grams_per_gram   IS DISTINCT FROM OLD.equivalent_grams_per_gram
  OR NEW.daily_equivalent_grams_cap  IS DISTINCT FROM OLD.daily_equivalent_grams_cap
  OR NEW.daily_concentrate_grams_cap IS DISTINCT FROM OLD.daily_concentrate_grams_cap
  OR NEW.effective_from              IS DISTINCT FROM OLD.effective_from
  OR NEW.change_reason               IS DISTINCT FROM OLD.change_reason
  OR NEW.published_by                IS DISTINCT FROM OLD.published_by
  OR NEW.published_at                IS DISTINCT FROM OLD.published_at
  OR NEW.reauthenticated_at          IS DISTINCT FROM OLD.reauthenticated_at
  OR NEW.supersedes_rule_id          IS DISTINCT FROM OLD.supersedes_rule_id
  OR NEW.notes                       IS DISTINCT FROM OLD.notes
  OR NEW.created_at                  IS DISTINCT FROM OLD.created_at
  THEN
    RAISE EXCEPTION
      'purchase_limit_rules is immutable: publish a new version instead of editing rule %',
      OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Closing the window is permitted exactly once, from NULL. A second close
  -- would move a boundary that orders have already been checked against.
  IF OLD.effective_until IS NOT NULL
     AND NEW.effective_until IS DISTINCT FROM OLD.effective_until THEN
    RAISE EXCEPTION
      'rule % was already closed at %; its window cannot be moved',
      OLD.id, OLD.effective_until
      USING ERRCODE = 'restrict_violation';
  END IF;

  -- Same for the forward pointer: one successor, recorded once.
  IF OLD.superseded_by_rule_id IS NOT NULL
     AND NEW.superseded_by_rule_id IS DISTINCT FROM OLD.superseded_by_rule_id THEN
    RAISE EXCEPTION
      'rule % already records a successor', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

CREATE TRIGGER "purchase_limit_rules_immutable"
  BEFORE UPDATE ON "purchase_limit_rules"
  FOR EACH ROW EXECUTE FUNCTION purchase_limit_rules_guard();--> statement-breakpoint

CREATE TRIGGER "purchase_limit_rules_no_delete"
  BEFORE DELETE ON "purchase_limit_rules"
  FOR EACH ROW EXECUTE FUNCTION purchase_limit_rules_guard();