CREATE TABLE "scheduler_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"job" varchar(60) NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"outcome" varchar(20) NOT NULL,
	"scanned" integer DEFAULT 0 NOT NULL,
	"expired" integer DEFAULT 0 NOT NULL,
	"units_released" integer DEFAULT 0 NOT NULL,
	"failed" integer DEFAULT 0 NOT NULL,
	"duration_ms" integer,
	"error" text
);
--> statement-breakpoint
CREATE INDEX "scheduler_runs_job_started_idx" ON "scheduler_runs" USING btree ("job","started_at");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Hand-written from here. NOT generated by drizzle-kit.
--
-- OVERLAP BECOMES IMPOSSIBLE, NOT MERELY UNLIKELY.
--
-- Until now "exactly one rule governs a class at any instant" was maintained by
-- a row lock and a partial unique index on the OPEN row. That is enough for the
-- publish path as written, and it is not a guarantee: the unique index says
-- nothing about two CLOSED windows overlapping, and any future code path — a
-- backfill, a data fix, a migration written in a hurry — could produce a pair
-- that checkout would then have to choose between.
--
-- An exclusion constraint states the invariant itself: for a given class, no
-- two effective windows may intersect. It is checked on every insert and every
-- update, by the database, forever, regardless of which code wrote the row.
--
-- Empty windows are exempt by construction rather than by a WHERE clause: a
-- cancelled rule has effective_from = effective_until, tstzrange() of which is
-- empty, and an empty range overlaps nothing. That is why cancelling a
-- scheduled change by giving it a zero-length window is safe.
--
-- btree_gist supplies the equality operator class for the enum column. The
-- obvious-looking `(cannabis_class)::text WITH =` does NOT work: the enum-to-
-- text cast is STABLE rather than IMMUTABLE — enum labels can be renamed — and
-- Postgres refuses it in an index expression. btree_gist covers enum types
-- directly, so the column is used as it is.
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS btree_gist;--> statement-breakpoint

ALTER TABLE "purchase_limit_rules"
  ADD CONSTRAINT "purchase_limit_rules_no_overlap"
  EXCLUDE USING gist (
    "cannabis_class" WITH =,
    tstzrange("effective_from", "effective_until") WITH &&
  );