CREATE TYPE "public"."measurement_basis" AS ENUM('net_weight_grams', 'finished_net_weight_grams', 'finished_volume_fluid_ounces', 'unit_count', 'exempt');--> statement-breakpoint
ALTER TYPE "public"."cannabis_class" ADD VALUE 'infused_solid' BEFORE 'edible';--> statement-breakpoint
ALTER TYPE "public"."cannabis_class" ADD VALUE 'infused_liquid' BEFORE 'edible';--> statement-breakpoint
ALTER TYPE "public"."cannabis_class" ADD VALUE 'immature_plant' BEFORE 'edible';--> statement-breakpoint
ALTER TYPE "public"."cannabis_class" ADD VALUE 'non_cannabis' BEFORE 'edible';--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "total_equivalent_grams" SET DATA TYPE numeric(12, 5);--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "total_concentrate_grams" SET DATA TYPE numeric(12, 5);--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ALTER COLUMN "equivalent_grams_per_gram" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ALTER COLUMN "daily_equivalent_grams_cap" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "product_variants" ADD COLUMN "measurement_basis" "measurement_basis";--> statement-breakpoint
ALTER TABLE "product_variants" ADD COLUMN "measurement_value" numeric(12, 4);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "measurement_basis" "measurement_basis";--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "measurement_value" numeric(12, 4);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "measurement_unit" varchar(16);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "usable_equivalent_grams" numeric(12, 5);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "immature_plant_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "equivalence_numerator" numeric(30, 0);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "equivalence_denominator" numeric(30, 0);--> statement-breakpoint
ALTER TABLE "order_lines" ADD COLUMN "calculation_version" integer;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "total_immature_plants" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "equivalence_numerator" numeric(30, 0);--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "equivalence_denominator" numeric(30, 0);--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "expected_basis" "measurement_basis";--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "usable_equivalent_cap_grams" numeric(12, 5);--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "concentrate_cap_grams" numeric(12, 5);--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "immature_plant_cap_units" integer;--> statement-breakpoint
ALTER TABLE "purchase_limit_rules" ADD COLUMN "calculation_version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Hand-written from here. NOT generated by drizzle-kit.
--
-- THE NEW VALUE COLUMNS MUST BE FROZEN TOO.
--
-- The guard installed in 0009 and revised in 0010 lists the columns that may
-- never change after publication. Adding columns without adding them to that
-- list would leave the conversion ratio, the three caps and the measurement
-- basis freely editable — which is to say it would move every number that
-- actually decides a legal limit OUTSIDE the protection built to guard them,
-- while the deprecated decimal it replaced stayed locked down.
--
-- Same policy as before: value columns permanent from the moment they are
-- written; `effective_until` movable only while it is still in the future;
-- `superseded_by_rule_id` writable once; DELETE always refused.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION purchase_limit_rules_guard() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION
      'purchase_limit_rules is append-only: rule % may not be deleted', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.id                          IS DISTINCT FROM OLD.id
  OR NEW.cannabis_class              IS DISTINCT FROM OLD.cannabis_class
  OR NEW.version                     IS DISTINCT FROM OLD.version
  OR NEW.equivalent_grams_per_gram   IS DISTINCT FROM OLD.equivalent_grams_per_gram
  OR NEW.daily_equivalent_grams_cap  IS DISTINCT FROM OLD.daily_equivalent_grams_cap
  OR NEW.daily_concentrate_grams_cap IS DISTINCT FROM OLD.daily_concentrate_grams_cap
  -- Added in 0013: the columns that now decide the limits.
  OR NEW.equivalence_numerator       IS DISTINCT FROM OLD.equivalence_numerator
  OR NEW.equivalence_denominator     IS DISTINCT FROM OLD.equivalence_denominator
  OR NEW.expected_basis              IS DISTINCT FROM OLD.expected_basis
  OR NEW.usable_equivalent_cap_grams IS DISTINCT FROM OLD.usable_equivalent_cap_grams
  OR NEW.concentrate_cap_grams       IS DISTINCT FROM OLD.concentrate_cap_grams
  OR NEW.immature_plant_cap_units    IS DISTINCT FROM OLD.immature_plant_cap_units
  OR NEW.calculation_version         IS DISTINCT FROM OLD.calculation_version
  OR NEW.effective_from              IS DISTINCT FROM OLD.effective_from
  OR NEW.change_reason               IS DISTINCT FROM OLD.change_reason
  OR NEW.published_by                IS DISTINCT FROM OLD.published_by
  OR NEW.published_at                IS DISTINCT FROM OLD.published_at
  OR NEW.reauthenticated_at          IS DISTINCT FROM OLD.reauthenticated_at
  OR NEW.supersedes_rule_id          IS DISTINCT FROM OLD.supersedes_rule_id
  OR NEW.notes                       IS DISTINCT FROM OLD.notes
  OR NEW.created_at                  IS DISTINCT FROM OLD.created_at
  THEN
    RAISE EXCEPTION
      'purchase_limit_rules is immutable: publish a new version instead of editing rule %',
      OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  IF NEW.effective_until IS DISTINCT FROM OLD.effective_until THEN
    IF OLD.effective_until IS NOT NULL AND OLD.effective_until <= now() THEN
      RAISE EXCEPTION
        'rule % closed at %, which has already passed; that boundary cannot be moved',
        OLD.id, OLD.effective_until
        USING ERRCODE = 'restrict_violation';
    END IF;

    IF NEW.effective_until IS NULL THEN
      RAISE EXCEPTION
        'rule % cannot be reopened once closed', OLD.id
        USING ERRCODE = 'restrict_violation';
    END IF;

    IF NEW.effective_until < now() - interval '1 minute' THEN
      RAISE EXCEPTION
        'rule % cannot be closed in the past', OLD.id
        USING ERRCODE = 'restrict_violation';
    END IF;
  END IF;

  IF OLD.superseded_by_rule_id IS NOT NULL
     AND NEW.superseded_by_rule_id IS DISTINCT FROM OLD.superseded_by_rule_id THEN
    RAISE EXCEPTION
      'rule % already records a successor', OLD.id
      USING ERRCODE = 'restrict_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;