ALTER TYPE "public"."audit_event" ADD VALUE 'CATALOG_COMPLIANCE_CHANGED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'CATALOG_COMPLIANCE_REJECTED';--> statement-breakpoint
ALTER TYPE "public"."audit_event" ADD VALUE 'CHECKOUT_BLOCKED_BY_GATE';--> statement-breakpoint
ALTER TYPE "public"."admin_permission" ADD VALUE 'catalog_compliance_admin';--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Hand-written from here. NOT generated by drizzle-kit.
--
-- THE CLASSIFICATION MATRIX, AS A DATABASE CONSTRAINT.
--
-- `lib/catalog/compliance.ts` enforces exactly these rules server-side, and
-- checkout refuses anything that fails them. This is the same statement made
-- where no application can route around it: a data fix, a restore, a migration
-- written in a hurry, or a future admin screen that forgets to validate.
--
-- IT IS DELIBERATELY NOT VALIDATED AGAINST EXISTING ROWS.
--
-- `NOT VALID` means the constraint applies to every INSERT and UPDATE from now
-- on, while leaving the 33 development variants — and any real catalog that
-- predates this — untouched and unsellable rather than un-migratable. Adding it
-- as a validating constraint would fail outright on any database with legacy
-- rows, and "make the migration pass" would mean rewriting classifications,
-- which is precisely the automatic guessing this phase refuses to do.
--
-- Those rows are already refused by checkout and already listed by
-- `verify:catalog`. They are fixed by a person, through the admin screen, and
-- the constraint stops any NEW row from joining them.
--
-- Run `ALTER TABLE product_variants VALIDATE CONSTRAINT
-- product_variants_compliance_matrix;` once the catalog is clean — it takes a
-- SHARE UPDATE EXCLUSIVE lock, not an ACCESS EXCLUSIVE one, so it does not
-- block reads or writes.
-- ---------------------------------------------------------------------------

ALTER TABLE "product_variants"
  ADD CONSTRAINT "product_variants_compliance_matrix"
  CHECK (
    -- Legacy and unclassified rows: permitted to exist, never sellable.
    -- Checkout, the bag and the readiness gate all refuse them.
    cannabis_class IN ('other', 'edible')

    -- flower and concentrate: net cannabis weight, positive grams.
    OR (cannabis_class IN ('flower', 'concentrate')
        AND measurement_basis = 'net_weight_grams'
        AND measurement_value IS NOT NULL
        AND measurement_value > 0)

    -- Solid infused: FINISHED-product net weight, positive grams.
    OR (cannabis_class = 'infused_solid'
        AND measurement_basis = 'finished_net_weight_grams'
        AND measurement_value IS NOT NULL
        AND measurement_value > 0)

    -- Liquid infused: FINISHED-product volume, positive fluid ounces.
    OR (cannabis_class = 'infused_liquid'
        AND measurement_basis = 'finished_volume_fluid_ounces'
        AND measurement_value IS NOT NULL
        AND measurement_value > 0)

    -- Immature plants: counted, positive, and WHOLE.
    OR (cannabis_class = 'immature_plant'
        AND measurement_basis = 'unit_count'
        AND measurement_value IS NOT NULL
        AND measurement_value > 0
        AND measurement_value = trunc(measurement_value))

    -- Explicitly exempt merchandise: no measurement at all. A value here is a
    -- contradiction — either the item is outside the calculation or it is not.
    OR (cannabis_class = 'non_cannabis'
        AND measurement_basis = 'exempt'
        AND measurement_value IS NULL)
  ) NOT VALID;